// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopinka;

namespace Shopinka.Migrations
{
    [DbContext(typeof(ShopinkaContext))]
    [Migration("20211018132718_ProductTableInitialDataSeed")]
    partial class ProductTableInitialDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shopinka.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vášeň ukrytá v čokoláde. Čokoláda je jedným z najväčších pokušení aké si človek len môže predstaviť. ",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Arónia osudu",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Čokoláda je jedným z najväčších pokušení aké si človek len môže predstaviť. ",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Karamelový anjelik",
                            Price = 0.69m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chrumkavá vášeň ukrytá v čokoláde. Jemná príchuť kubánskeho rumu.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Rumová chrumka",
                            Price = 2.69m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chrumkavá vášeň ukrytá v čokoláde. Dotyk jahôdok. ",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Jahodová chrumka",
                            Price = 1.69m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vášeň ukrytá v čokoláde. Okoreňte si svoj život. ",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Čili chrumka",
                            Price = 0.39m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vášeň ukrytá v čokoláde. Espresso shot v čokoláde. ",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Kávička v čokoláde",
                            Price = 2.39m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Prekvapenie.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Double trouble",
                            Price = 1.39m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Zážitok.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Agent Provocateur",
                            Price = 0.79m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Najpredávanejšia pralinka.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Mandľové praliné",
                            Price = 2.79m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Luxusná variácia najpredávanejšej pralinky.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Lieskovoorieškové praliné",
                            Price = 1.79m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Čokoládová ganache s dotykom najkvalitnejšej borovičky.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Čože je to borovička",
                            Price = 0.49m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Čokoládová ganache s dotykom najkvalitnejšej slivovičky.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Čože je to slivovička",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Herbal infusion. Upokojujúca chuť harmančeka v sladkom objatí bielej čokolády.",
                            ImageUri = "https://elezi.sk/wp-content/uploads/2019/08/photo_21-02-2019_14_18_01-upr_1.jpg",
                            Name = "Harmančekové pohladenie",
                            Price = 1.49m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
